#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///

"""
site-builder — Full-stack Next.js site generator
Usage: uv run build.py new ./project [--vertical dental] [--brand "#hex1,#hex2"] [--name "Client Name"]
"""

import argparse
import json
import os
import shutil
from pathlib import Path as _Path
import sys as _sys

# Shared git utilities
_sys.path.insert(0, str(_Path(__file__).parent.parent.parent / "_shared/scripts"))
try:
    from git_utils import ensure_git_repo, Worktree, commit_all, is_git_repo
    HAS_GIT_UTILS = True
except ImportError:
    HAS_GIT_UTILS = False
import subprocess
import sys
import textwrap
from pathlib import Path

SKILL_DIR = Path(__file__).parent.parent
DATA_DIR = SKILL_DIR / "data"
TEMPLATES_DIR = SKILL_DIR / "templates"

# ── Colors ───────────────────────────────────────────────────────────────────
R="\033[0m"; BOLD="\033[1m"; RED="\033[31m"; GRN="\033[32m"
YLW="\033[33m"; BLU="\033[34m"; CYN="\033[36m"; DIM="\033[2m"

def ok(m): print(f"  {GRN}✅{R}  {m}")
def warn(m): print(f"  {YLW}⚠️ {R}  {m}")
def err(m): print(f"  {RED}❌{R}  {m}")
def info(m): print(f"  {BLU}→{R}  {m}")
def header(m): print(f"\n{BOLD}{CYN}{m}{R}")
def rule(): print(f"  {DIM}{'─'*55}{R}")

def load_verticals():
    path = DATA_DIR / "verticals.json"
    return json.loads(path.read_text())["verticals"]

def ask(prompt, default=""):
    val = input(f"  {YLW}?{R}  {prompt}{f' [{default}]' if default else ''}: ").strip()
    return val or default

def pick_vertical(verticals):
    header("AVAILABLE VERTICALS")
    for i, (key, v) in enumerate(verticals.items(), 1):
        print(f"  {DIM}{i:2}.{R} {BOLD}{key}{R}  {DIM}— {v['name']}{R}")
    print()
    choice = ask("Vertical key (or number)")
    if choice.isdigit():
        keys = list(verticals.keys())
        idx = int(choice) - 1
        if 0 <= idx < len(keys):
            return keys[idx]
    if choice in verticals:
        return choice
    err(f"Unknown vertical: {choice}")
    sys.exit(1)

# ── Design System Generator ───────────────────────────────────────────────────
def generate_design_system(vertical_key: str, vertical: dict, brand_colors: list, project_name: str, domain: str) -> str:
    primary = brand_colors[0] if brand_colors else vertical["colors"]["primary"]
    accent = brand_colors[1] if len(brand_colors) > 1 else vertical["colors"]["accent"]

    shadcn_list = ", ".join(vertical["shadcn"])
    sections_list = "\n".join(f"  - {s}" for s in vertical["sections"])
    anti_list = "\n".join(f"  - {a}" for a in vertical["anti_patterns"])
    seo_list = "\n".join(f"  - {s}" for s in vertical["seo_intent"])
    trust_list = "\n".join(f"  - {t}" for t in vertical["trust_signals"])

    return f"""# Design System — {project_name}
Generated by site-builder | Vertical: {vertical_key}

---

## Project
- **Name:** {project_name}
- **Domain:** {domain}
- **Vertical:** {vertical['name']}
- **Pattern:** {vertical['pattern']}
- **Style:** {vertical['style']}
- **Mood:** {vertical['mood']}

---

## Colors

```css
:root {{
  --color-primary: {primary};
  --color-accent: {accent};
  --color-bg: {vertical['colors']['bg']};
  --color-surface: {vertical['colors']['surface']};
  --color-text: {vertical['colors']['text']};
}}
```

Use: 60% primary/bg, 30% surface/secondary, 10% accent.
All text must meet WCAG AA (4.5:1 contrast ratio minimum).

---

## Typography

- **Display font:** {vertical['fonts']['display']}
- **Body font:** {vertical['fonts']['body']}
- **Scale:** 12 / 14 / 16 / 18 / 20 / 24 / 32 / 40 / 48 / 60px
- **Line height:** 1.5 body, 1.1 display headings
- **Max 2 font families. No Inter/Roboto/Arial as display.**

---

## Page Sections (in order)

{sections_list}

---

## shadcn Components to Install

```bash
npx shadcn@latest add {shadcn_list}
```

---

## Trust Signals (must include)

{trust_list}

---

## SEO Intent Keywords

{seo_list}

---

## Lead Capture
- **Type:** {vertical['lead_capture']}
- Must fire to Supabase (fire-and-forget) on submit
- Source field: "{vertical_key}"

---

## Hero Image
Prompt for generation:
"{vertical['hero_image']}"

Command:
```bash
source ~/.openclaw/.env && uv run ~/.openclaw/skills/image-gen/scripts/generate.py \\
  --prompt "{vertical['hero_image']}" \\
  --provider openai --model best --aspect-ratio "16:9" \\
  --filename "public/assets/hero.png"
```

---

## Anti-Patterns (NEVER use)

{anti_list}

---

## Design Quality Checklist (from design-for-ai)

**Before shipping, verify:**

Typography
- [ ] Max 2 font families
- [ ] No Inter/Roboto/Arial as primary display
- [ ] Correct line heights (1.5 body, 1.1 display)
- [ ] No fake bold

Color
- [ ] 60/30/10 rule applied
- [ ] All text passes WCAG AA (4.5:1)
- [ ] No decorative gradient text
- [ ] Hue-shifted shadows

Composition
- [ ] One dominant element per section
- [ ] No 6x identical card grids
- [ ] Generous whitespace between sections
- [ ] Intentional asymmetry where possible

Motion
- [ ] 100ms micro / 300ms standard / 500ms complex
- [ ] prefers-reduced-motion respected
- [ ] Animations convey information, not decoration

AI Tells (eliminate all)
- [ ] No Inter as the only font
- [ ] No cyan-on-dark or purple-to-blue gradient
- [ ] No identical icon+heading+text repeated N times
- [ ] No everything-centered layout
- [ ] No same spacing throughout
- [ ] No glassmorphism used decoratively
- [ ] No glowing neon in dark mode
- [ ] No everything fades up with same timing

Interaction States
- [ ] All 8 states defined: default/hover/focus/active/disabled/loading/error/success

Responsive
- [ ] Works at 375px / 768px / 1024px / 1440px
- [ ] Fluid typography (clamp())
- [ ] 44×44px minimum touch targets
- [ ] Mobile-first CSS

---
*Generated by site-builder — do not edit manually. Regenerate with site-builder if vertical changes.*
"""

# ── AGENT_TASK.md Generator ───────────────────────────────────────────────────
def generate_agent_task(vertical_key: str, vertical: dict, project_name: str, domain: str, project_dir: Path) -> str:
    sections_detail = "\n".join(
        f"- **{s}** — [describe purpose/copy direction for {project_name}]"
        for s in vertical["sections"]
    )

    return f"""# Agent Task — {project_name}

> Generated by site-builder. Read design-system/MASTER.md first, then execute every task below.

## Project
- **Name:** {project_name}
- **Domain:** {domain}
- **Vertical:** {vertical['name']} ({vertical_key})
- **Stack:** Next.js 16 + Tailwind v4 + TypeScript
- **Project dir:** {project_dir}

---

## Step 0: Read Design System
Read `design-system/MASTER.md` completely before writing any code.
All colors, fonts, components must match the spec exactly.

---

## Step 1: Install shadcn Components
```bash
npx shadcn@latest init  # if not already initialized
npx shadcn@latest add {' '.join(vertical['shadcn'])}
```

---

## Step 2: Set Brand CSS Variables
In `src/app/globals.css`, ensure CSS variables are set to brand colors.
Reference: design-system/MASTER.md Color section.

---

## Step 3: Build All Page Sections

{sections_detail}

**Rules for every component:**
- Mobile-first (375px)
- Uses CSS variables for all colors (never hardcode hex)
- Uses display font var for headings, body font for paragraphs
- 44px minimum tap targets
- All 8 interaction states (default/hover/focus/active/disabled/loading/error/success)
- No AI tells (see design-system/MASTER.md Anti-Patterns)
- prefers-reduced-motion respected for all animations

---

## Step 4: Lead Capture Form
- Type: {vertical['lead_capture']}
- On submit: fire to Supabase `pace_leads` table (fire-and-forget, never block submit)
- Source field: "{vertical_key}"
- Import submitLead from `@/lib/submit-lead`
- Keep existing form delivery (Formspree or whatever is configured) as primary

---

## Step 5: SEO
- One `<h1>` per page
- Proper h1 → h2 → h3 hierarchy
- JSON-LD LocalBusiness schema in layout.tsx
- Meta title + description targeting: {', '.join(vertical['seo_intent'][:3])}
- OG meta (og:title, og:description, og:image, twitter:card)
- robots.ts: allow all AI crawlers (GPTBot, ClaudeBot, anthropic-ai, PerplexityBot)

---

## Step 6: Trust Signals
Include these on the page:
{chr(10).join(f'- {t}' for t in vertical['trust_signals'])}

---

## Step 7: Performance
- `priority` prop on all above-fold images
- `quality={{100}}` on hero image
- Correct `width` and `height` on all next/image components
- Lazy load below-fold images
- Font preloading in layout.tsx `<head>`

---

## Step 8: Build Check
```bash
npm run build
```
Fix ALL TypeScript errors and warnings. Build must be clean before finishing.

---

## When Done
Run:
```bash
openclaw system event --text "Build complete: {project_name} — {project_dir.name} ready for review" --mode now
```
"""

# ── Project Scaffold ──────────────────────────────────────────────────────────
def scaffold_project(project_dir: Path, vertical_key: str, vertical: dict,
                     project_name: str, domain: str, brand_colors: list, dry_run: bool):

    header("SCAFFOLDING PROJECT")

    if project_dir.exists() and any(project_dir.iterdir()):
        if not dry_run:
            answer = ask(f"{project_dir} already exists and has files. Overwrite?", "n")
            if answer.lower() != "y":
                err("Cancelled")
                sys.exit(1)

    # Check for base template
    base_template = TEMPLATES_DIR / "base"
    if base_template.exists():
        if not dry_run:
            if project_dir.exists():
                shutil.rmtree(project_dir)
            shutil.copytree(base_template, project_dir)
            ok(f"Copied base template to {project_dir}")
        else:
            info(f"[dry-run] Would copy base template → {project_dir}")
    else:
        # No template yet — use create-next-app
        if not dry_run:
            info("No base template found — scaffolding with create-next-app...")
            result = subprocess.run(
                f"npx create-next-app@latest {project_dir} --typescript --tailwind --app --no-src-dir --no-import-alias --yes",
                shell=True, capture_output=True, text=True
            )
            if result.returncode != 0:
                err(f"create-next-app failed: {result.stderr[:300]}")
                sys.exit(1)
            ok("Next.js project created")
        else:
            info(f"[dry-run] Would run create-next-app → {project_dir}")

    if dry_run:
        return

    # Write design system
    ds_dir = project_dir / "design-system"
    ds_dir.mkdir(exist_ok=True)
    ds_content = generate_design_system(vertical_key, vertical, brand_colors, project_name, domain)
    (ds_dir / "MASTER.md").write_text(ds_content)
    ok("design-system/MASTER.md written")

    # Write AGENT_TASK.md
    task_content = generate_agent_task(vertical_key, vertical, project_name, domain, project_dir)
    (project_dir / "AGENT_TASK.md").write_text(task_content)
    ok("AGENT_TASK.md written")

    # Write .deploy.json
    deploy_config = {
        "env_file": ".env.local",
        "asset_min_kb": 200,
        "hero_patterns": ["hero", "step", "about", "feature", "banner"],
        "smoke_urls": [
            {"path": "/", "expect": 200},
            {"path": "/sitemap.xml", "expect": 200},
            {"path": "/robots.txt", "expect": 200}
        ]
    }
    (project_dir / ".deploy.json").write_text(json.dumps(deploy_config, indent=2))
    ok(".deploy.json written")

    # Write .env.local stub
    env_stub = f"""# {project_name} — Environment Variables
# Fill these in before deploying

NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_KEY=

# Dashboard auth (if using /dashboard)
DASHBOARD_PASSWORD=
DASHBOARD_JWT_SECRET=

# Google Places (if using address autocomplete)
NEXT_PUBLIC_GOOGLE_PLACES_API_KEY=

# Forms (if using Formspree)
NEXT_PUBLIC_FORMSPREE_ID=
"""
    env_path = project_dir / ".env.local"
    if not env_path.exists():
        env_path.write_text(env_stub)
        ok(".env.local stub created")

    # Inject brand colors into globals.css if it exists
    globals_css = project_dir / "src/app/globals.css"
    if not globals_css.exists():
        globals_css = project_dir / "app/globals.css"

    if globals_css.exists():
        primary = brand_colors[0] if brand_colors else vertical["colors"]["primary"]
        accent = brand_colors[1] if len(brand_colors) > 1 else vertical["colors"]["accent"]
        color_vars = f"""
/* Site-builder: Brand CSS Variables */
:root {{
  --color-primary: {primary};
  --color-accent: {accent};
  --color-bg: {vertical['colors']['bg']};
  --color-surface: {vertical['colors']['surface']};
  --color-text: {vertical['colors']['text']};
}}
"""
        existing = globals_css.read_text()
        if "--color-primary" not in existing:
            globals_css.write_text(existing + color_vars)
            ok("Brand CSS variables injected into globals.css")

    # Generate hero image
    info(f"Hero image prompt: {vertical['hero_image'][:60]}...")
    hero_assets_dir = project_dir / "public/assets"
    hero_assets_dir.mkdir(parents=True, exist_ok=True)
    image_gen = Path.home() / ".openclaw/skills/image-gen/scripts/generate.py"
    if image_gen.exists():
        info("Generating hero image with gpt-image-1.5 (background)...")
        subprocess.Popen(
            f"source ~/.openclaw/.env && uv run {image_gen} "
            f'--prompt "{vertical["hero_image"]}" '
            f"--provider openai --model best --aspect-ratio 16:9 "
            f"--filename {hero_assets_dir}/hero.png",
            shell=True, executable="/bin/zsh",
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
        )
        info("Hero image generating in background (~30s)")
    else:
        warn("image-gen skill not found — generate hero image manually")

    # Initialize git repo and make initial commit
    if HAS_GIT_UTILS:
        ensure_git_repo(project_dir)
        # Make initial commit of scaffold
        import subprocess as _sp
        _sp.run("git add -A", shell=True, cwd=project_dir, capture_output=True)
        r = _sp.run('git commit -m "Initial scaffold (site-builder)"',
                    shell=True, cwd=project_dir, capture_output=True)
        if r.returncode == 0:
            ok("Initial git commit created — ready for worktree-based development")

# ── Commands ──────────────────────────────────────────────────────────────────
def cmd_verticals(args):
    verticals = load_verticals()
    header(f"AVAILABLE VERTICALS ({len(verticals)})")
    rule()
    for key, v in verticals.items():
        print(f"  {BOLD}{key:<25}{R}  {DIM}{v['name']}{R}")
        print(f"  {'':25}  {DIM}Style: {v['style']} · Pattern: {v['pattern']}{R}")
        print()

def cmd_design(args):
    verticals = load_verticals()
    vertical_key = args.vertical or pick_vertical(verticals)
    vertical = verticals[vertical_key]
    brand_colors = [c.strip() for c in args.brand.split(",")] if args.brand else []
    project_name = args.name or vertical["name"]
    domain = args.domain or "example.com"

    header(f"DESIGN SYSTEM — {project_name}")
    ds = generate_design_system(vertical_key, vertical, brand_colors, project_name, domain)
    print(ds)

def cmd_new(args):
    if not args.project_dir:
        err("Provide a project directory: site-builder new ./my-project")
        sys.exit(1)

    verticals = load_verticals()
    project_dir = Path(args.project_dir).resolve()

    print(f"\n{BOLD}{'━'*60}{R}")
    print(f"{BOLD}  🏗️  site-builder — new project{R}")
    if args.dry_run:
        print(f"  {YLW}DRY RUN — nothing will be executed{R}")
    print(f"{BOLD}{'━'*60}{R}")

    # Collect inputs
    vertical_key = args.vertical or pick_vertical(verticals)
    vertical = verticals[vertical_key]

    brand_input = args.brand or ask("Brand colors (hex, comma-separated)", f"{vertical['colors']['primary']},{vertical['colors']['accent']}")
    brand_colors = [c.strip() for c in brand_input.split(",") if c.strip()]

    project_name = args.name or ask("Project/client name", vertical["name"])
    domain = args.domain or ask("Domain", "example.com")

    # Summary
    header("PLAN")
    rule()
    print(f"  {DIM}Project:{R}    {project_dir}")
    print(f"  {DIM}Vertical:{R}   {vertical['name']}")
    print(f"  {DIM}Style:{R}      {vertical['style']}")
    print(f"  {DIM}Fonts:{R}      {vertical['fonts']['display']} / {vertical['fonts']['body']}")
    print(f"  {DIM}Colors:{R}     {' · '.join(brand_colors)}")
    print(f"  {DIM}Sections:{R}   {', '.join(vertical['sections'][:4])}...")
    print(f"  {DIM}shadcn:{R}     {', '.join(vertical['shadcn'][:4])}...")
    rule()
    print()

    if not args.dry_run and not args.yes:
        confirm = ask("Build this project?", "y")
        if confirm.lower() != "y":
            err("Cancelled")
            sys.exit(0)

    scaffold_project(project_dir, vertical_key, vertical, project_name, domain, brand_colors, args.dry_run)

    if not args.dry_run:
        header("NEXT STEPS")
        rule()
        ok(f"Project ready at {project_dir}")
        print()
        info("1. Fill in .env.local with your API keys")
        info("2. Hand to Claude Code:")
        print(f"\n  {DIM}cd {project_dir}{R}")
        print(f"  {DIM}claude --permission-mode bypassPermissions --print \"Read AGENT_TASK.md and execute it\"{R}")
        print()
        info("3. Deploy when done:")
        print(f"  {DIM}uv run ~/.openclaw/skills/nextjs-deploy/scripts/deploy.py {project_dir}{R}")
        rule()
        print()

def cmd_audit(args):
    if not args.project_dir:
        err("Provide a project directory: site-builder audit ./my-project")
        sys.exit(1)
    project_dir = Path(args.project_dir).resolve()
    header(f"DESIGN AUDIT — {project_dir.name}")
    info("Audit feature coming soon — use design-for-ai checker for now")
    info("Install: claude '/plugin marketplace add ryanthedev/rtd-claude-inn'")

# ── Entry Point ───────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="site-builder — Next.js site generator")
    sub = parser.add_subparsers(dest="command")

    # new
    p_new = sub.add_parser("new", help="Scaffold a new project")
    p_new.add_argument("project_dir", nargs="?")
    p_new.add_argument("--vertical", help="Vertical key (e.g. dental, saas)")
    p_new.add_argument("--brand", help="Brand colors: '#hex1,#hex2'")
    p_new.add_argument("--name", help="Project/client name")
    p_new.add_argument("--domain", help="Domain name")
    p_new.add_argument("--dry-run", action="store_true")
    p_new.add_argument("--yes", "-y", action="store_true", help="Skip confirmations")

    # verticals
    sub.add_parser("verticals", help="List all available verticals")

    # design
    p_design = sub.add_parser("design", help="Generate design system only")
    p_design.add_argument("--vertical")
    p_design.add_argument("--brand")
    p_design.add_argument("--name")
    p_design.add_argument("--domain")

    # audit
    p_audit = sub.add_parser("audit", help="Audit an existing project")
    p_audit.add_argument("project_dir", nargs="?")

    args = parser.parse_args()

    if args.command == "new":
        cmd_new(args)
    elif args.command == "verticals":
        cmd_verticals(args)
    elif args.command == "design":
        cmd_design(args)
    elif args.command == "audit":
        cmd_audit(args)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
